import './globals.css'
import { Dosis, Lato, Pacifico } from 'next/font/google'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const fontHeading = Dosis({
  weight: ["800"],
  subsets: ["latin"],
  variable: "--font-heading",
});

const fontCursive = Pacifico({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-cursive",
});

const fontDescription = Lato({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-description",
});

const fontDescriptionBold = Lato({
  weight: ["700"],
  subsets: ["latin"],
  variable: "--font-description-bold",
});


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${fontHeading.variable} ${fontCursive.variable} ${fontDescription.variable} ${fontDescriptionBold.variable} bg-retroradcool-150`}>
        {children}
      </body>
    </html>
  )
}
